"""Adding the is_active field to the table sneaker_size_associations

Revision ID: 7865f2cadef2
Revises: a5692b0b6adf
Create Date: 2025-12-27 07:49:32.318814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7865f2cadef2"
down_revision: Union[str, None] = "a5692b0b6adf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneaker_size_associations",
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneaker_size_associations", "is_active")
    # ### end Alembic commands ###
