from sqlalchemy.ext.asyncio import AsyncSession

from stock_notification_service.stock_notification.models import Sneaker


async def seed_sneakers(db: AsyncSession):
    sneakers = [
        Sneaker(
            name="Air Max 90",
            brand_id=1,
            image_url="/uploads/sneakers/nike_air_max.png",
        ),
        Sneaker(
            name="Yellow",
            brand_id=1,
            image_url="/uploads/sneakers/nike_yellow.jpg",
        ),
        Sneaker(
            name="AL8",
            brand_id=1,
            image_url="/uploads/sneakers/nike_al8.png",
        ),
        Sneaker(
            name="DH",
            brand_id=1,
            image_url="/uploads/sneakers/nike_dh.jpeg",
        ),
        Sneaker(
            name="DN",
            brand_id=1,
            image_url="/uploads/sneakers/nike_dn.jpg",
        ),
        Sneaker(
            name="Jordan",
            brand_id=1,
            image_url="/uploads/sneakers/nike_jordan.jpg",
        ),
        Sneaker(
            name="React",
            brand_id=1,
            image_url="/uploads/sneakers/nike_react.jpg",
        ),
        Sneaker(
            name="Intertop",
            brand_id=1,
            image_url="/uploads/sneakers/nike_intertop.jpg",
        ),
        Sneaker(
            name="Ferrari",
            brand_id=3,
            image_url="/uploads/sneakers/puma_ferrari.jpg",
        ),
        Sneaker(
            name="Palermo",
            brand_id=3,
            image_url="/uploads/sneakers/puma_palermo.png",
        ),
        Sneaker(
            name="Park",
            brand_id=3,
            image_url="/uploads/sneakers/puma_Park.png",
        ),
        Sneaker(
            name="Roma",
            brand_id=3,
            image_url="/uploads/sneakers/puma_Roma.jpg",
        ),
        Sneaker(
            name="RS-X",
            brand_id=3,
            image_url="/uploads/sneakers/puma_rs-x.png",
        ),
        Sneaker(
            name="SL",
            brand_id=3,
            image_url="/uploads/sneakers/puma_sl.png",
        ),
        Sneaker(
            name="Suede",
            brand_id=3,
            image_url="/uploads/sneakers/puma_suede.jpg",
        ),
        Sneaker(
            name="Trinity",
            brand_id=3,
            image_url="/uploads/sneakers/puma_trinity.jpg",
        ),
        Sneaker(
            name="Authetic",
            brand_id=4,
            image_url="/uploads/sneakers/vans_authetic.png",
        ),
        Sneaker(
            name="Hevy",
            brand_id=4,
            image_url="/uploads/sneakers/vans_hevy.png",
        ),
        Sneaker(
            name="Old",
            brand_id=4,
            image_url="/uploads/sneakers/vans_old.jpg",
        ),
        Sneaker(
            name="Old Scholl",
            brand_id=4,
            image_url="/uploads/sneakers/vans_old_scholl.png",
        ),
        Sneaker(
            name="Primary",
            brand_id=4,
            image_url="/uploads/sneakers/vans_Primary.png",
        ),
        Sneaker(
            name="Ssk8",
            brand_id=4,
            image_url="/uploads/sneakers/vans_Sk8.png",
        ),
        Sneaker(
            name="Skooll",
            brand_id=4,
            image_url="/uploads/sneakers/vans_skool.png",
        ),
        Sneaker(
            name="Slip",
            brand_id=4,
            image_url="/uploads/sneakers/vans_slip.jpg",
        ),
        Sneaker(
            name="Centennial",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_centennial.jpg",
        ),
        Sneaker(
            name="Byuty",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_daroga.jpg",
        ),
        Sneaker(
            name="Eclyptix",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_eclyptix.png",
        ),
        Sneaker(
            name="Fenesi",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_fenesi.jpg",
        ),
        Sneaker(
            name="Ozweego",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_ozweego.png",
        ),
        Sneaker(
            name="Runfalcon",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_runfalcon.jpg",
        ),
        Sneaker(
            name="Temper",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_runfalcon.png",
        ),
        Sneaker(
            name="Daffy",
            brand_id=2,
            image_url="/uploads/sneakers/adidas_temper.jpg",
        ),
    ]

    db.add_all(sneakers)
    await db.flush()
    await db.commit()
