"""Add field size_id in model FavoriteSneakerAssociation

Revision ID: 62b82ba88faf
Revises: c7842bd4c08b
Create Date: 2025-12-13 06:06:23.862966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62b82ba88faf"
down_revision: Union[str, None] = "c7842bd4c08b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorite_sneaker_associations",
        sa.Column("size_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_column("favorite_sneaker_associations", "size_id")
    # ### end Alembic commands ###
