"""Adding the is_active field to the table sneaker_size_associations

Revision ID: a930903f32ad
Revises: 6939d8d498dd
Create Date: 2025-12-27 07:53:02.165661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a930903f32ad"
down_revision: Union[str, None] = "6939d8d498dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneaker_size_associations",
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneaker_size_associations", "is_active")
    # ### end Alembic commands ###
