services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_auth
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  favorite_db:
    image: postgres:16-alpine
    container_name: favorite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_favorite
    volumes:
      - favorite_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  cart_db:
    image: postgres:16-alpine
    container_name: cart_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_cart
    volumes:
      - cart_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  catalog_db:
    image: postgres:16-alpine
    container_name: catalog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_catalog
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  sneaker_details_db:
    image: postgres:16-alpine
    container_name: sneaker_details_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_sneaker_details
    volumes:
      - sneaker_details_pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  auth_test_db:
    image: postgres:16-alpine
    container_name: auth_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_test_auth
    volumes:
      - auth_test_pgdata:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  favorite_test_db:
    image: postgres:16-alpine
    container_name: favorite_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_test_favorite
    volumes:
      - favorite_test_pgdata:/var/lib/postgresql/data
    ports:
      - "5443:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  cart_test_db:
    image: postgres:16-alpine
    container_name: cart_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_test_cart
    volumes:
      - cart_test_pgdata:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  catalog_test_db:
    image: postgres:16-alpine
    container_name: catalog_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_test_catalog
    volumes:
      - catalog_test_pgdata:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  sneaker_details_test_db:
    image: postgres:16-alpine
    container_name: sneaker_details_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_test_sneaker_details
    volumes:
      - sneaker_details_test_pgdata:/var/lib/postgresql/data
    ports:
      - "5446:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  auth_service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      auth_db:
        condition: service_healthy
      auth_test_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/auth_service:/app/auth_service
      - ./backend/secrets:/app/secrets
      - ./kafka:/app/auth_service/kafka
      - ./redis_client/redis_connection:/app/auth_service/redis_client/redis_connection
    ports:
      - "8002:8002"
    working_dir: /app/auth_service
    command: [ "python", "-m", "uvicorn", "auth_service.main:app", "--host", "0.0.0.0", "--port", "8002" , "--reload" ]
    restart: unless-stopped


  auth_alembic:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: auth_alembic_migrations
    depends_on:
      auth_db:
        condition: service_healthy
      auth_test_db:
        condition: service_healthy
    working_dir: /app/auth_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/auth_service:/app/auth_service
      - ./backend/secrets:/app/secrets
      - ./kafka:/app/auth_service/kafka
      - ./redis_client/redis_connection:/app/auth_service/redis_client/redis_connection
    command: [ "upgrade", "head" ]


  favorite_service:
    build:
      context: ./backend/favorite_service
      dockerfile: Dockerfile
    container_name: favorite_service
    depends_on:
      favorite_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/favorite_service:/app/favorite_service
      - ./kafka:/app/favorite_service/kafka
      - ./redis_client/redis_connection:/app/favorite_service/redis_client/redis_connection
    ports:
      - "8003:8003"
    working_dir: /app/favorite_service
    command: [ "python", "-m", "uvicorn", "favorite_service.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload" ]
    restart: unless-stopped


  favorite_alembic:
    build:
      context: ./backend/favorite_service
      dockerfile: Dockerfile
    container_name: favorite_alembic_migrations
    depends_on:
      favorite_db:
        condition: service_healthy
    working_dir: /app/favorite_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/favorite_service:/app/favorite_service
      - ./kafka:/app/favorite_service/kafka
      - ./redis_client/redis_connection:/app/favorite_service/redis_client/redis_connection
    command: [ "upgrade", "head" ]


  cart_service:
    build:
      context: ./backend/cart_service
      dockerfile: Dockerfile
    container_name: cart_service
    depends_on:
      cart_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/cart_service:/app/cart_service
      - ./kafka:/app/cart_service/kafka
      - ./redis_client/redis_connection:/app/cart_service/redis_client/redis_connection
    ports:
      - "8004:8004"
    working_dir: /app/cart_service
    command: [ "python", "-m", "uvicorn", "cart_service.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload" ]
    restart: unless-stopped


  cart_alembic:
    build:
      context: ./backend/cart_service
      dockerfile: Dockerfile
    container_name: cart_alembic_migrations
    depends_on:
      cart_db:
        condition: service_healthy
    working_dir: /app/cart_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/cart_service:/app/cart_service
      - ./kafka:/app/cart_service/kafka
      - ./redis_client/redis_connection:/app/cart_service/redis_client/redis_connection
    command: [ "upgrade", "head" ]


  catalog_service:
    build:
      context: ./backend/catalog_service
      dockerfile: Dockerfile
    container_name: catalog_service
    depends_on:
      catalog_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./backend/catalog_service:/app/catalog_service
      - ./kafka:/app/catalog_service/kafka
    ports:
      - "8005:8005"
    command: [ "python", "-m", "uvicorn", "catalog_service.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload" ]
    restart: unless-stopped


  catalog_alembic:
    build:
      context: ./backend/catalog_service
      dockerfile: Dockerfile
    container_name: catalog_alembic_migrations
    depends_on:
      catalog_db:
        condition: service_healthy
    working_dir: /app/catalog_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/catalog_service:/app/catalog_service
    command: [ "upgrade", "head" ]


  sneaker_details_service:
    build:
      context: ./backend/sneaker_details_service
      dockerfile: Dockerfile
    container_name: sneaker_details_service
    depends_on:
      sneaker_details_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/sneaker_details_service:/app/sneaker_details_service
      - ./kafka:/app/sneaker_details_service/kafka
      - ./redis_client/redis_connection:/app/sneaker_details_service/redis_client/redis_connection
    ports:
      - "8006:8006"
    command: [ "python", "-m", "uvicorn", "sneaker_details_service.main:app", "--host", "0.0.0.0", "--port", "8006", "--reload" ]
    restart: unless-stopped


  sneaker_details_alembic:
    build:
      context: ./backend/sneaker_details_service
      dockerfile: Dockerfile
    container_name: sneaker_details_alembic_migrations
    depends_on:
      sneaker_details_db:
        condition: service_healthy
    working_dir: /app/sneaker_details_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/sneaker_details_service:/app/sneaker_details_service
      - ./redis_client/redis_connection:/app/sneaker_details_service/redis_client/redis_connection
    command: [ "upgrade", "head" ]


  sneaker_views_redis_writer:
    build:
      context: ./backend/sneaker_views_redis_writer
      dockerfile: Dockerfile
    container_name: sneaker_views_redis_writer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./backend/sneaker_views_redis_writer:/app/sneaker_views_redis_writer
      - ./kafka:/app/sneaker_views_redis_writer/kafka
      - ./redis_client/redis_connection:/app/sneaker_views_redis_writer/redis_client/redis_connection
    ports:
      - "8007:8007"
    working_dir: /app/sneaker_views_redis_writer
    command: [ "python", "-m", "uvicorn", "sneaker_views_redis_writer.main:app", "--host", "0.0.0.0", "--port", "8007", "--reload" ]
    restart: unless-stopped


  sneaker_views_clickhouse_writer:
    build:
      context: ./backend/sneaker_views_clickhouse_writer
      dockerfile: Dockerfile
    container_name: sneaker_views_clickhouse_writer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./backend/sneaker_views_clickhouse_writer:/app/sneaker_views_clickhouse_writer
      - ./kafka:/app/sneaker_views_clickhouse_writer/kafka
    ports:
      - "8008:8008"
    working_dir: /app/sneaker_views_clickhouse_writer
    command: [ "python", "-m", "uvicorn", "sneaker_views_clickhouse_writer.main:app", "--host", "0.0.0.0", "--port", "8008", "--reload" ]
    restart: unless-stopped


  sneaker_views_clickhouse_alembic:
    build:
      context: ./backend/sneaker_views_clickhouse_writer
      dockerfile: Dockerfile
    container_name: sneaker_views_alembic_migrations
    depends_on:
      clickhouse:
        condition: service_healthy
    working_dir: /app/sneaker_views_clickhouse_writer
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/sneaker_views_clickhouse_writer:/app/sneaker_views_clickhouse_writer
      - ./kafka:/app/sneaker_views_clickhouse_writer/kafka
      - ./clickhouse/clickhouse_connection:/app/sneaker_views_clickhouse_writer/clickhouse/clickhouse_connection
    command: [ "upgrade", "head" ]


  user_history_service:
    build:
      context: ./backend/user_history_service
      dockerfile: Dockerfile
    container_name: user_history_service
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ./backend/user_history_service:/app/user_history_service
      - ./redis_client/redis_connection:/app/user_history_service/redis_client/redis_connection
    ports:
      - "8009:8009"
    working_dir: /app/user_history_service
    command: [ "python", "-m", "uvicorn", "user_history_service.main:app", "--host", "0.0.0.0", "--port", "8009", "--reload" ]
    restart: unless-stopped


  kong-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kong" ]
      interval: 10s
      timeout: 5s
      retries: 5


  kong:
    image: kong:latest
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong

      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"   # для входящих HTTP-запросов (Proxy)
      - "8443:8443"   # для входящих HTTPS-запросов (Proxy)
      - "8001:8001"   # для Admin API (HTTP)
      - "8444:8444"   # для Admin API (HTTPS)
    command: >
      sh -c "kong migrations bootstrap && kong start"
    volumes:
      - ./kong/kong.yml:/opt/kong/kong.yml


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka-kraft

    ports:
      - "9092:9092"   # клиенты (produce/fetch)
      - "9093:9093"   # внутренняя связь контроллера

    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_KRAFT_CLUSTER_ID: "01234567-89ab-cdef-0123-456789abcdef"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-kraft:9093"

      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - kafka-data:/bitnami/kafka


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend_builder
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend


  redis:
    image: redis:latest
    container_name: project-redis-1
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_client/redis_data:/data
      - ./redis_client/redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5


  redis_cache:
    image: redis:latest
    container_name: project-redis-cache-1
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./redis_client/redis_cache_data:/data
      - ./redis_client/redis_config/redis_cache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5


  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
    volumes:
      - ./clickhouse/clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/clickhouse_log:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_USER: "kirill"
      CLICKHOUSE_PASSWORD: "Meteor906587"
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query='SELECT 1' --user=kirill --password=Meteor906587" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  sneaker_check_price_bot:
    build:
      context: ./sneaker_check_price_bot
      dockerfile: Dockerfile
    container_name: sneaker_check_price_bot
    working_dir: /app/sneaker_check_price_bot
    command: [ "python", "-m", "sneaker_bot.main" ]
    restart: unless-stopped

volumes:
  auth_pgdata:
  favorite_pgdata:
  cart_pgdata:
  catalog_pgdata:
  sneaker_details_pgdata:
  auth_test_pgdata:
  kong-data:
  kafka-data:
  favorite_test_pgdata:
  cart_test_pgdata:
  catalog_test_pgdata:
  sneaker_details_test_pgdata: