version: "3.8"

services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_auth
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  favorite_db:
    image: postgres:16-alpine
    container_name: favorite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_favorite
    volumes:
      - favorite_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cart_db:
    image: postgres:16-alpine
    container_name: cart_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_cart
    volumes:
      - cart_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog_db:
    image: postgres:16-alpine
    container_name: catalog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meteor906587
      POSTGRES_DB: sneaker_shop_catalog
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      auth_db:
        condition: service_healthy
    volumes:
      - ./backend/secrets:/app/secrets
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@auth_db:5432/sneaker_shop_auth
    command: ["python", "-m", "uvicorn", "auth_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  auth_alembic:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: alembic_migrations
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@auth_db:5432/sneaker_shop_auth
    working_dir: /app/auth_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/auth_service:/app/auth_service
      - ./backend/secrets:/app/secrets
    command: [ "upgrade", "head" ]


  favorite_service:
    build:
      context: ./backend/favorite_service
      dockerfile: Dockerfile
    container_name: favorite_service
    depends_on:
      favorite_db:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@favorite_db:5432/sneaker_shop_favorite
    command: ["python", "-m", "uvicorn", "favorite_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: unless-stopped

  favorite_alembic:
    build:
      context: ./backend/favorite_service
      dockerfile: Dockerfile
    container_name: favorite_alembic_migrations
    depends_on:
      favorite_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@favorite_db:5432/sneaker_shop_favorite
    working_dir: /app/favorite_service
    entrypoint: ["poetry", "run", "alembic", "-c", "alembic.ini"]
    volumes:
      - ./backend/favorite_service:/app/favorite_service
    command: ["upgrade", "head"]

  cart_service:
    build:
      context: ./backend/cart_service
      dockerfile: Dockerfile
    container_name: cart_service
    depends_on:
      cart_db:
        condition: service_healthy
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@cart_db:5432/sneaker_shop_cart
    command: ["python", "-m", "uvicorn", "cart_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
    restart: unless-stopped

  cart_alembic:
    build:
      context: ./backend/cart_service
      dockerfile: Dockerfile
    container_name: cart_alembic_migrations
    depends_on:
      cart_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@cart_db:5432/sneaker_shop_cart
    working_dir: /app/cart_service
    entrypoint: ["poetry", "run", "alembic", "-c", "alembic.ini"]
    volumes:
      - ./backend/cart_service:/app/cart_service
    command: ["upgrade", "head"]

  catalog_service:
    build:
      context: ./backend/catalog_service
      dockerfile: Dockerfile
    container_name: catalog_service
    depends_on:
      catalog_db:
        condition: service_healthy
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@catalog_db:5432/sneaker_shop_catalog
    command: [ "python", "-m", "uvicorn", "catalog_service.main:app", "--host", "0.0.0.0", "--port", "8003" ]
    restart: unless-stopped

  catalog_alembic:
    build:
      context: ./backend/catalog_service
      dockerfile: Dockerfile
    container_name: catalog_alembic_migrations
    depends_on:
      catalog_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:meteor906587@catalog_db:5432/sneaker_shop_catalog
    working_dir: /app/catalog_service
    entrypoint: [ "poetry", "run", "alembic", "-c", "alembic.ini" ]
    volumes:
      - ./backend/catalog_service:/app/catalog_service
    command: [ "upgrade", "head" ]

volumes:
  auth_pgdata:
  favorite_pgdata:
  cart_pgdata:
  catalog_pgdata:
