"""Refinement of table field properties

Revision ID: a5692b0b6adf
Revises: e73d84a0c1b1
Create Date: 2025-12-27 07:39:07.572482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5692b0b6adf"
down_revision: Union[str, None] = "e73d84a0c1b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.create_unique_constraint(
        op.f("uq_brands_image_url"), "brands", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_brands_name"), "brands", ["name"])
    op.drop_index(
        op.f("ix_cart_sneaker_associations_cart_id"),
        table_name="cart_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_cart_sneaker_associations_size_id"),
        table_name="cart_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_cart_sneaker_associations_sneaker_id"),
        table_name="cart_sneaker_associations",
    )
    op.create_unique_constraint(
        "uq_cart_sneaker_size",
        "cart_sneaker_associations",
        ["cart_id", "sneaker_id", "size_id"],
    )
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.create_unique_constraint(op.f("uq_carts_user_id"), "carts", ["user_id"])
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(op.f("ix_sneakers_name"), table_name="sneakers")
    op.create_unique_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_sneakers_name"), "sneakers", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sneakers_name"), "sneakers", type_="unique")
    op.drop_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", type_="unique"
    )
    op.create_index(
        op.f("ix_sneakers_name"), "sneakers", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_carts_user_id"), "carts", type_="unique")
    op.create_index(
        op.f("ix_carts_user_id"), "carts", ["user_id"], unique=True
    )
    op.drop_constraint(
        "uq_cart_sneaker_size", "cart_sneaker_associations", type_="unique"
    )
    op.create_index(
        op.f("ix_cart_sneaker_associations_sneaker_id"),
        "cart_sneaker_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cart_sneaker_associations_size_id"),
        "cart_sneaker_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cart_sneaker_associations_cart_id"),
        "cart_sneaker_associations",
        ["cart_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_brands_name"), "brands", type_="unique")
    op.drop_constraint(op.f("uq_brands_image_url"), "brands", type_="unique")
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    # ### end Alembic commands ###
