"""Added the quantity field to the cart_sneakers table

Revision ID: ae1dd5faab74
Revises: 7d2a36319ee4
Create Date: 2025-10-10 21:48:08.080311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae1dd5faab74"
down_revision: Union[str, None] = "7d2a36319ee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_sneaker_associations",
        sa.Column("quantity", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_sneaker_associations", "quantity")
    # ### end Alembic commands ###
