"""Indexes on Foreign keys have been added

Revision ID: e73d84a0c1b1
Revises: bcf84de164a8
Create Date: 2025-12-20 05:18:15.414289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e73d84a0c1b1"
down_revision: Union[str, None] = "bcf84de164a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_cart_sneaker_associations_cart_id"),
        "cart_sneaker_associations",
        ["cart_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cart_sneaker_associations_size_id"),
        "cart_sneaker_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cart_sneaker_associations_sneaker_id"),
        "cart_sneaker_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_cart_sneaker_associations_sneaker_id"),
        table_name="cart_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_cart_sneaker_associations_size_id"),
        table_name="cart_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_cart_sneaker_associations_cart_id"),
        table_name="cart_sneaker_associations",
    )
    # ### end Alembic commands ###
