"""In the cart_sneaker_associations table, the sneaker_size field has been replaced with the size_id field, with the secret key to sizes.id

Revision ID: 425629f79663
Revises: 195ff4a86259
Create Date: 2025-10-14 09:38:01.744311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "425629f79663"
down_revision: Union[str, None] = "195ff4a86259"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_sneaker_associations",
        sa.Column("size_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_cart_sneaker_associations_size_id_sizes"),
        "cart_sneaker_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.drop_column("cart_sneaker_associations", "sneaker_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_sneaker_associations",
        sa.Column(
            "sneaker_size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_cart_sneaker_associations_size_id_sizes"),
        "cart_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_column("cart_sneaker_associations", "size_id")
    # ### end Alembic commands ###
