"""Indexes on Foreign keys have been added

Revision ID: c83ab191dbec
Revises: fde5eeacd1de
Create Date: 2025-12-20 05:23:44.644358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c83ab191dbec"
down_revision: Union[str, None] = "fde5eeacd1de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    # ### end Alembic commands ###
