"""Adding the is_active field to the table sneaker_size_associations

Revision ID: 78a2d1f40298
Revises: 33611ea43879
Create Date: 2025-12-27 07:51:00.966587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78a2d1f40298"
down_revision: Union[str, None] = "33611ea43879"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneaker_size_associations",
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneaker_size_associations", "is_active")
    # ### end Alembic commands ###
