"""Refinement of table field properties

Revision ID: 33611ea43879
Revises: c83ab191dbec
Create Date: 2025-12-27 07:40:01.982772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33611ea43879"
down_revision: Union[str, None] = "c83ab191dbec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.create_unique_constraint(
        op.f("uq_brands_image_url"), "brands", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_brands_name"), "brands", ["name"])
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(op.f("ix_sneakers_name"), table_name="sneakers")
    op.create_unique_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_sneakers_name"), "sneakers", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sneakers_name"), "sneakers", type_="unique")
    op.drop_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", type_="unique"
    )
    op.create_index(
        op.f("ix_sneakers_name"), "sneakers", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_brands_name"), "brands", type_="unique")
    op.drop_constraint(op.f("uq_brands_image_url"), "brands", type_="unique")
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    # ### end Alembic commands ###
