from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from microservices.sneaker_details_service.sneaker_details_service.sneaker_details.models import Sneaker


async def seed_sneakers(session: AsyncSession):
    sneakers = [
        {
            "name": "Air Zoom Pegasus",
            "description": "Лёгкие беговые кроссовки для ежедневных тренировок и пробежек.",
            "price": 399.99,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_pegasus.png",
        },
        {
            "name": "Ultraboost Classic",
            "description": "Комфортные кроссовки с амортизацией для городских прогулок.",
            "price": 429.50,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_ultraboost.png",
        },
        {
            "name": "RS-X Bold",
            "description": "Яркие и массивные кроссовки в стиле ретро с выразительным дизайном.",
            "price": 349.00,
            "brand_id": 3,
            "country_id": 5,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/puma_rsx.png",
        },
        {
            "name": "Old Skool Canvas",
            "description": "Классические кеды на каждый день с прочной подошвой.",
            "price": 270.00,
            "brand_id": 4,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_oldskool.png",
        },
        {
            "name": "XT-6 Trail",
            "description": "Треккинговые кроссовки для бездорожья и экстремальных условий.",
            "price": 460.00,
            "brand_id": 5,
            "country_id": 15,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_xt6.png",
        },
        {
            "name": "Gel-Kayano 28",
            "description": "Стабильные беговые кроссовки с поддержкой стопы и амортизацией.",
            "price": 420.50,
            "brand_id": 6,
            "country_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/asics_kayano.png",
        },
        {
            "name": "Fresh Foam X",
            "description": "Мягкая амортизация и лёгкость для длительных пробежек.",
            "price": 389.00,
            "brand_id": 7,
            "country_id": 9,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/newbalance_freshfoam.png",
        },
        {
            "name": "Classic Leather",
            "description": "Икона стиля от Reebok, подходит для повседневной носки.",
            "price": 310.00,
            "brand_id": 8,
            "country_id": 9,
            "gender": "женские",
            "image_url": "/uploads/sneakers/reebok_classic.png",
        },
        {
            "name": "Chuck Taylor All Star",
            "description": "Легендарные кеды Converse, универсальный городской стиль.",
            "price": 280.00,
            "brand_id": 9,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/converse_chuck.png",
        },
        {
            "name": "Air Jordan 1",
            "description": "Культовая модель Jordan с ретро‑силуэтом и премиальными материалами.",
            "price": 520.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_1.png",
        },
        {
            "name": "HOVR Phantom",
            "description": "Технологичные кроссовки Under Armour с отличной амортизацией.",
            "price": 375.00,
            "brand_id": 11,
            "country_id": 16,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/underarmour_hovr.png",
        },
        {
            "name": "Kinvara Lite",
            "description": "Лёгкие и отзывчивые кроссовки для скоростных тренировок.",
            "price": 299.99,
            "brand_id": 12,
            "country_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/saucony_kinvara.png",
        },
        {
            "name": "Disruptor II",
            "description": "Массивные кроссовки Fila в стиле 90-х с выраженной подошвой.",
            "price": 299.99,
            "brand_id": 13,
            "country_id": 17,
            "gender": "женские",
            "image_url": "/uploads/sneakers/fila_disruptor.png",
        },
        {
            "name": "Hoka Clifton",
            "description": "Максимальная мягкость и комфорт для длительных пробежек.",
            "price": 410.00,
            "brand_id": 14,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/hoka_clifton.png",
        },
        {
            "name": "Wave Rider",
            "description": "Стабильные кроссовки Mizuno с технологией амортизации Wave.",
            "price": 365.00,
            "brand_id": 15,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/mizuno_waverider.png",
        },
        {
            "name": "Diadora N9000",
            "description": "Ретро‑модель с современными материалами и комфортной посадкой.",
            "price": 330.00,
            "brand_id": 16,
            "country_id": 5,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/diadora_n9000.png",
        },
        {
            "name": "Brooks Ghost",
            "description": "Надёжные беговые кроссовки для ежедневных тренировок.",
            "price": 359.00,
            "brand_id": 17,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/brooks_ghost.png",
        },
        {
            "name": "Kappa Retro",
            "description": "Стильные кроссовки в ретро‑стиле для повседневной носки.",
            "price": 245.00,
            "brand_id": 18,
            "country_id": 11,
            "gender": "женские",
            "image_url": "/uploads/sneakers/kappa_retro.png",
        },
        {
            "name": "Trail Runner Pro",
            "description": "Универсальные трейловые кроссовки для пересечённой местности.",
            "price": 439.00,
            "brand_id": 5,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_trail.png",
        },
        {
            "name": "City Walker",
            "description": "Комфортные кроссовки для прогулок по городу и повседневной носки.",
            "price": 219.99,
            "brand_id": 8,
            "country_id": 9,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/reebok_citywalker.png",
        },
        {
            "name": "Skate Pro",
            "description": "Прочные кеды для скейтбординга с усиленной носочной частью.",
            "price": 289.00,
            "brand_id": 4,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_skatepro.png",
        },
        {
            "name": "Court Classic",
            "description": "Классические теннисные кроссовки с лаконичным дизайном.",
            "price": 255.00,
            "brand_id": 9,
            "country_id": 12,
            "gender": "женские",
            "image_url": "/uploads/sneakers/converse_court.png",
        },
        {
            "name": "Speedster",
            "description": "Лёгкие соревновательные кроссовки для спринта и трека.",
            "price": 499.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_speedster.png",
        },
        {
            "name": "Everyday Comfort",
            "description": "Универсальные кроссовки с мягкой стелькой для повседневной носки.",
            "price": 199.99,
            "brand_id": 7,
            "country_id": 16,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/newbalance_everyday.png",
        },
        {
            "name": "Court Ace",
            "description": "Лёгкие и стильные кроссовки для активного отдыха и спорта.",
            "price": 279.50,
            "brand_id": 2,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_courtace.png",
        },
        {
            "name": "Urban Runner",
            "description": "Городские кроссовки с усиленной подошвой и стильным дизайном.",
            "price": 325.00,
            "brand_id": 3,
            "country_id": 5,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/puma_urbanrunner.png",
        },
        {
            "name": "Retro Runner",
            "description": "Ретро‑кроссовки с современной амортизацией и комфортной посадкой.",
            "price": 289.99,
            "brand_id": 13,
            "country_id": 17,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/fila_retrorunner.png",
        },
        {
            "name": "All Terrain GTX",
            "description": "Водонепроницаемые кроссовки с мембраной Gore-Tex для любых погодных условий.",
            "price": 499.99,
            "brand_id": 5,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_gtx.png",
        },
        {
            "name": "Minimal Trainer",
            "description": "Лёгкие минималистичные кроссовки для тренировок и зала.",
            "price": 219.00,
            "brand_id": 12,
            "country_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/saucony_minimal.png",
        },
        {
            "name": "Heritage Classic",
            "description": "Элегантные повседневные кроссовки с премиальной отделкой.",
            "price": 349.00,
            "brand_id": 8,
            "country_id": 11,
            "gender": "женские",
            "image_url": "/uploads/sneakers/reebok_heritage.png",
        },
        {
            "name": "Air Force 1 Low",
            "description": "Классические кроссовки Nike Air Force 1 с прочной кожей и универсальным стилем.",
            "price": 329.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_low.png",
        },
        {
            "name": "Dunk Low Retro",
            "description": "Ретро‑Dunk с контрастными панелями и винтажным видом.",
            "price": 349.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_low.png",
        },
        {
            "name": "Jordan 4 Retro",
            "description": "Jordan 4 с узнаваемым силуэтом и премиальными материалами.",
            "price": 599.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4.png",
        },
        {
            "name": "Jordan 11 Concord",
            "description": "Легендарная Jordan 11 с глянцевой накладкой и элегантным дизайном.",
            "price": 749.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_concord.png",
        },
        {
            "name": "Jordan 5 Retro",
            "description": "Jordan 5 с выразительной подошвой и сетчатыми вставками.",
            "price": 529.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5.png",
        },
        {
            "name": "Jordan 6 Retro",
            "description": "Jordan 6 — культовая модель с характерной формой и поддержкой.",
            "price": 549.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_6.png",
        },
        {
            "name": "Jordan 7 Retro",
            "description": "Jordan 7 с яркими цветовыми акцентами и комфортной посадкой.",
            "price": 499.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_7.png",
        },
        {
            "name": "Air Force 1 High",
            "description": "Высокая версия Air Force 1 с дополнительной фиксацией и ретро‑стилем.",
            "price": 349.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_high.png",
        },
        {
            "name": "Dunk High Premium",
            "description": "Высокие Dunk с премиальными материалами и насыщенными цветами.",
            "price": 369.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_high.png",
        },
        {
            "name": "Air Force 1 Shadow",
            "description": "Модернизированная AF1 с наложениями и многослойным дизайном.",
            "price": 339.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_af1_shadow.png",
        },
        {
            "name": "Superstar Classic",
            "description": "Культовая adidas Superstar с кожаным верхом и резиновым носком.",
            "price": 299.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar.png",
        },
        {
            "name": "Spezial OG",
            "description": "Adidas Spezial — ретро‑стиль и премиальные материалы для улицы.",
            "price": 319.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial.png",
        },
        {
            "name": "Forum Low",
            "description": "Ретро‑баскетбольная модель adidas Forum в современной интерпретации.",
            "price": 289.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_forum.png",
        },
        {
            "name": "Yeezy Runner (inspired)",
            "description": "Современная модель с минималистичным дизайном и мягкой подошвой.",
            "price": 429.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_yeezy_like.png",
        },
        {
            "name": "Campus 80s",
            "description": "Классика adidas Campus с бархатистой замшей и лаконичным силуэтом.",
            "price": 279.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_campus.png",
        },
        {
            "name": "Gazelle Vintage",
            "description": "Лёгкая ретро‑модель Gazelle с тонким профилем и замшевым верхом.",
            "price": 259.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_gazelle.png",
        },
        {
            "name": "Stan Smith Premium",
            "description": "Икона минимализма — Stan Smith в премиальном исполнении.",
            "price": 299.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_stansmith.png",
        },
        {
            "name": "Superstar Bold",
            "description": "Модификация Superstar с увеличенной подошвой и яркими акцентами.",
            "price": 329.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_superstar_bold.png",
        },
        {
            "name": "Dame Retro (inspired)",
            "description": "Баскетбольный ретро‑силуэт с современной подошвой и поддержкой.",
            "price": 279.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_dame_like.png",
        },
        {
            "name": "Spezial Low",
            "description": "Низкая версия Spezial с акцентом на детали и комфорт.",
            "price": 309.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial_low.png",
        },
        {
            "name": "Air Force 1 Utility",
            "description": "AF1 с утилитарными элементами и дополнительными карманами.",
            "price": 359.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_utility.png",
        },
        {
            "name": "Dunk SB Pro",
            "description": "Skate‑ориентированная версия Dunk с усиленной подошвой и амортизацией.",
            "price": 379.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_sb.png",
        },
        {
            "name": "Jordan 4 Retro SE",
            "description": "Специальная версия Jordan 4 с уникальными материалами и отделкой.",
            "price": 629.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4_se.png",
        },
        {
            "name": "Jordan 5 Off-White (inspired)",
            "description": "Коллаб‑стиль с характерными элементами и нестандартной отделкой.",
            "price": 699.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5_collab.png",
        },
        {
            "name": "Superstar Platform",
            "description": "Superstar с приподнятой платформой для модного образа.",
            "price": 339.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_superstar_platform.png",
        },
        {
            "name": "Dunk Low Premium Pack",
            "description": "Набор Dunk Low с премиальными материалами и лимитированными расцветками.",
            "price": 389.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_premium.png",
        },
        {
            "name": "Jordan 11 Retro Low",
            "description": "Низкая версия Jordan 11 с узнаваемой глянцевой вставкой.",
            "price": 699.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_low.png",
        },
        {
            "name": "Air Force 1 Pixel",
            "description": "Современная вариация AF1 с пиксельными элементами и яркими акцентами.",
            "price": 349.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_pixel.png",
        },
        {
            "name": "Superstar Vintage",
            "description": "Винтажная версия Superstar с состаренной отделкой и ретро‑подошвой.",
            "price": 309.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar_vintage.png",
        },
        {
            "name": "Dunk Low City Pack",
            "description": "Городская серия Dunk Low с тематическими расцветками для улицы.",
            "price": 369.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_citypack.png",
        },
        {
            "name": "Air Force 1 Low Premium",
            "description": "Премиальная версия AF1 с улучшенной кожей и деталями.",
            "price": 359.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_premium.png",
        },
        {
            "name": "Dunk Low Retro OG",
            "description": "Ретро‑Dunk с классическими панелями и контрастными швами.",
            "price": 379.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_low_og.png",
        },
        {
            "name": "Jordan 4 Retro OG",
            "description": "Классическая Jordan 4 с узнаваемым профилем и премиальной отделкой.",
            "price": 619.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4_og.png",
        },
        {
            "name": "Jordan 11 Retro IE",
            "description": "Jordan 11 в облегчённой версии с фирменной глянцевой вставкой.",
            "price": 699.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_ie.png",
        },
        {
            "name": "Jordan 5 Retro Low",
            "description": "Низкая версия Jordan 5 с классическим дизайном и поддержкой.",
            "price": 529.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5_low.png",
        },
        {
            "name": "Superstar Core",
            "description": "Классическая adidas Superstar с резиновым носком и простым дизайном.",
            "price": 289.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar_core.png",
        },
        {
            "name": "Spezial Reissue",
            "description": "Переиздание Spezial с акцентом на детали и ретро‑стиль.",
            "price": 329.00,
            "brand_id": 2,
            "country_id": 6,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial_reissue.png",
        },
        {
            "name": "Air Jordan 6 Retro",
            "description": "Jordan 6 с узнаваемой формой и усиленной посадкой.",
            "price": 549.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_6_retro.png",
        },
        {
            "name": "Air Jordan 7 Retro Low",
            "description": "Низкая версия Jordan 7 с яркими цветовыми акцентами.",
            "price": 499.00,
            "brand_id": 10,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_7_low.png",
        },
        {
            "name": "Air Force 1 Utility Mid",
            "description": "Утилитарная версия AF1 с дополнительными креплениями и текстильными вставками.",
            "price": 369.00,
            "brand_id": 1,
            "country_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_utility_mid.png",
        },
    ]

    stmt = insert(Sneaker).values(sneakers)
    await session.execute(stmt)
    await session.commit()
