"""Create all tables

Revision ID: 116fcd2ecd80
Revises: 
Create Date: 2025-08-03 17:10:28.187083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116fcd2ecd80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_index(op.f('ix_colors_name'), 'colors', ['name'], unique=True)
    op.create_table('countrys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countrys'))
    )
    op.create_index(op.f('ix_countrys_name'), 'countrys', ['name'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=True)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_size', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.CheckConstraint('eu_size BETWEEN 15 AND 50', name=op.f('ck_sizes_check_eu_size_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('eu_size', name=op.f('uq_sizes_eu_size'))
    )
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_sneakers_check_price_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_sneakers_brand_id_brands')),
    sa.ForeignKeyConstraint(['country_id'], ['countrys.id'], name=op.f('fk_sneakers_country_id_countrys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sneakers'))
    )
    op.create_index(op.f('ix_sneakers_brand_id'), 'sneakers', ['brand_id'], unique=False)
    op.create_index(op.f('ix_sneakers_country_id'), 'sneakers', ['country_id'], unique=False)
    op.create_index(op.f('ix_sneakers_name'), 'sneakers', ['name'], unique=False)
    op.create_table('sneaker_color_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sneaker_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_sneaker_color_associations_color_id_colors')),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], name=op.f('fk_sneaker_color_associations_sneaker_id_sneakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sneaker_color_associations')),
    sa.UniqueConstraint('sneaker_id', 'color_id', name='uq_sneaker_color')
    )
    op.create_table('sneaker_material_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sneaker_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_sneaker_material_associations_material_id_materials')),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], name=op.f('fk_sneaker_material_associations_sneaker_id_sneakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sneaker_material_associations')),
    sa.UniqueConstraint('sneaker_id', 'material_id', name='uq_sneaker_material')
    )
    op.create_table('sneaker_size_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sneaker_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name=op.f('fk_sneaker_size_associations_size_id_sizes')),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], name=op.f('fk_sneaker_size_associations_sneaker_id_sneakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sneaker_size_associations')),
    sa.UniqueConstraint('sneaker_id', 'size_id', name='uq_sneaker_size')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sneaker_size_associations')
    op.drop_table('sneaker_material_associations')
    op.drop_table('sneaker_color_associations')
    op.drop_index(op.f('ix_sneakers_name'), table_name='sneakers')
    op.drop_index(op.f('ix_sneakers_country_id'), table_name='sneakers')
    op.drop_index(op.f('ix_sneakers_brand_id'), table_name='sneakers')
    op.drop_table('sneakers')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_countrys_name'), table_name='countrys')
    op.drop_table('countrys')
    op.drop_index(op.f('ix_colors_name'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
