"""Indexes on Foreign keys have been added

Revision ID: aface7f26fe4
Revises: 63fd389ff5e7
Create Date: 2025-12-20 05:25:19.525114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aface7f26fe4"
down_revision: Union[str, None] = "63fd389ff5e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sneaker_color_associations_color_id"),
        "sneaker_color_associations",
        ["color_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_color_associations_sneaker_id"),
        "sneaker_color_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_material_associations_material_id"),
        "sneaker_material_associations",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_material_associations_sneaker_id"),
        "sneaker_material_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_material_associations_sneaker_id"),
        table_name="sneaker_material_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_material_associations_material_id"),
        table_name="sneaker_material_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_color_associations_sneaker_id"),
        table_name="sneaker_color_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_color_associations_color_id"),
        table_name="sneaker_color_associations",
    )
    # ### end Alembic commands ###
