"""Added cascading deletion and restrict

Revision ID: 63fd389ff5e7
Revises: e04404f59385
Create Date: 2025-12-17 21:48:43.938002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63fd389ff5e7"
down_revision: Union[str, None] = "e04404f59385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countrys_name"), table_name="countries")
    op.create_index(
        op.f("ix_countries_name"), "countries", ["name"], unique=True
    )
    op.drop_constraint(
        op.f("fk_sneaker_color_associations_sneaker_id_sneakers"),
        "sneaker_color_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_color_associations_color_id_colors"),
        "sneaker_color_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_color_associations_sneaker_id_sneakers"),
        "sneaker_color_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_color_associations_color_id_colors"),
        "sneaker_color_associations",
        "colors",
        ["color_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneaker_material_associations_sneaker_id_sneakers"),
        "sneaker_material_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_material_associations_material_id_materials"),
        "sneaker_material_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_material_associations_sneaker_id_sneakers"),
        "sneaker_material_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_material_associations_material_id_materials"),
        "sneaker_material_associations",
        "materials",
        ["material_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        "countries",
        ["country_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_material_associations_material_id_materials"),
        "sneaker_material_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_material_associations_sneaker_id_sneakers"),
        "sneaker_material_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_material_associations_material_id_materials"),
        "sneaker_material_associations",
        "materials",
        ["material_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_material_associations_sneaker_id_sneakers"),
        "sneaker_material_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_color_associations_color_id_colors"),
        "sneaker_color_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_color_associations_sneaker_id_sneakers"),
        "sneaker_color_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_color_associations_color_id_colors"),
        "sneaker_color_associations",
        "colors",
        ["color_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_color_associations_sneaker_id_sneakers"),
        "sneaker_color_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.create_index(
        op.f("ix_countrys_name"), "countries", ["name"], unique=True
    )
    # ### end Alembic commands ###
