"""Adding the size_id field to the user_sneaker_subscriptions table

Revision ID: cb8c6f918d25
Revises: 0d0fef4039fc
Create Date: 2025-12-02 20:23:31.207405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb8c6f918d25"
down_revision: Union[str, None] = "0d0fef4039fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sneaker_subscriptions",
        sa.Column("size_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_user_sneaker"), "user_sneaker_subscriptions", type_="unique"
    )
    op.create_unique_constraint(
        "uq_user_sneaker_size",
        "user_sneaker_subscriptions",
        ["sneaker_id", "user_id", "size_id"],
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        "sizes",
        ["size_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_user_sneaker_size", "user_sneaker_subscriptions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_user_sneaker"),
        "user_sneaker_subscriptions",
        ["sneaker_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_sneaker_subscriptions", "size_id")
    # ### end Alembic commands ###
