"""Blacklist table created

Revision ID: 12bf59e6749e
Revises: abe953a1d52e
Create Date: 2025-08-15 17:17:40.716293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12bf59e6749e"
down_revision: Union[str, None] = "abe953a1d52e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklists",
        sa.Column("refresh_token_id", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_reason", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["refresh_token_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_blacklists_refresh_token_id_refresh_tokens"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blacklists")),
        sa.UniqueConstraint(
            "refresh_token_id", name=op.f("uq_blacklists_refresh_token_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blacklists")
    # ### end Alembic commands ###
