"""Refinement of table field properties

Revision ID: acac95520b2a
Revises: 1a86c455d5c7
Create Date: 2025-12-27 07:30:52.558857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acac95520b2a"
down_revision: Union[str, None] = "1a86c455d5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_blacklists_refresh_token_id"), table_name="blacklists"
    )
    op.create_unique_constraint(
        op.f("uq_permissions_name"), "permissions", ["name"]
    )
    op.drop_index(
        op.f("ix_role_permission_associations_permission_id"),
        table_name="role_permission_associations",
    )
    op.drop_index(
        op.f("ix_role_permission_associations_role_id"),
        table_name="role_permission_associations",
    )
    op.create_unique_constraint(op.f("uq_roles_name"), "roles", ["name"])
    op.drop_index(
        op.f("ix_user_role_associations_role_id"),
        table_name="user_role_associations",
    )
    op.drop_index(
        op.f("ix_user_role_associations_user_id"),
        table_name="user_role_associations",
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.create_index(
        op.f("ix_user_role_associations_user_id"),
        "user_role_associations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_role_associations_role_id"),
        "user_role_associations",
        ["role_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_roles_name"), "roles", type_="unique")
    op.create_index(
        op.f("ix_role_permission_associations_role_id"),
        "role_permission_associations",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permission_associations_permission_id"),
        "role_permission_associations",
        ["permission_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("uq_permissions_name"), "permissions", type_="unique"
    )
    op.create_index(
        op.f("ix_blacklists_refresh_token_id"),
        "blacklists",
        ["refresh_token_id"],
        unique=False,
    )
    # ### end Alembic commands ###
