"""Delete column sneaker_size in favorite_sneaker_associations

Revision ID: b7bbe8be3e01
Revises: 595f0c837999
Create Date: 2025-05-27 21:09:22.776649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7bbe8be3e01"
down_revision: Union[str, None] = "595f0c837999"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite_sneaker_associations", "sneaker_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorite_sneaker_associations",
        sa.Column(
            "sneaker_size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
