"""Create table material, sneaker_material

Revision ID: b1516ed9426c
Revises: 91f0b9c29bba
Create Date: 2025-05-15 17:28:36.139135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1516ed9426c"
down_revision: Union[str, None] = "91f0b9c29bba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    op.create_index(
        op.f("ix_materials_name"), "materials", ["name"], unique=True
    )
    op.create_table(
        "sneaker_material_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f(
                "fk_sneaker_material_associations_material_id_materials"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_sneaker_material_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_sneaker_material_associations")
        ),
        sa.UniqueConstraint(
            "sneaker_id", "material_id", name="uq_sneaker_material"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sneaker_material_associations")
    op.drop_index(op.f("ix_materials_name"), table_name="materials")
    op.drop_table("materials")
    # ### end Alembic commands ###
