"""Create favorites and favorite_sneaker_associations Tables

Revision ID: 595f0c837999
Revises: 7c31fa4d503e
Create Date: 2025-05-26 23:08:12.516221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "595f0c837999"
down_revision: Union[str, None] = "7c31fa4d503e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
    )
    op.create_index(
        op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=True
    )
    op.create_table(
        "favorite_sneaker_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("favorite_id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("sneaker_size", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["favorite_id"],
            ["favorites.id"],
            name=op.f(
                "fk_favorite_sneaker_associations_favorite_id_favorites"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_favorite_sneaker_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_favorite_sneaker_associations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorite_sneaker_associations")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_table("favorites")
    # ### end Alembic commands ###
