"""Create table countries, colors, sneaker_colors

Revision ID: 91f0b9c29bba
Revises: 4ecf9d6ff384
Create Date: 2025-05-15 16:55:11.069669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91f0b9c29bba"
down_revision: Union[str, None] = "4ecf9d6ff384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_colors")),
    )
    op.create_index(op.f("ix_colors_name"), "colors", ["name"], unique=True)
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
    )
    op.create_index(
        op.f("ix_countries_name"), "countries", ["name"], unique=True
    )
    op.create_table(
        "sneaker_color_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["colors.id"],
            name=op.f("fk_sneaker_color_associations_color_id_colors"),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_sneaker_color_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_sneaker_color_associations")
        ),
        sa.UniqueConstraint("sneaker_id", "color_id", name="uq_sneaker_color"),
    )
    op.add_column(
        "sneakers", sa.Column("country_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_sneakers_country_id"),
        "sneakers",
        ["country_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        "countries",
        ["country_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneakers_country_id_countries"),
        "sneakers",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_sneakers_country_id"), table_name="sneakers")
    op.drop_column("sneakers", "country_id")
    op.drop_table("sneaker_color_associations")
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_colors_name"), table_name="colors")
    op.drop_table("colors")
    # ### end Alembic commands ###
