"""Create cart_sneaker_associations Table

Revision ID: 7c31fa4d503e
Revises: 4f3540e063e7
Create Date: 2025-05-26 19:07:48.184208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c31fa4d503e"
down_revision: Union[str, None] = "4f3540e063e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_sneaker_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("sneaker_size", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
            name=op.f("fk_cart_sneaker_associations_cart_id_carts"),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_cart_sneaker_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_cart_sneaker_associations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_sneaker_associations")
    # ### end Alembic commands ###
