from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from sneaker_details_service.sneaker_details.models import Sneaker


async def seed_sneakers(session: AsyncSession):
    sneakers = [
        {
            "name": "Air Max 90",
            "description": "Лучшие кросовки своей линейки",
            "price": 215.99,
            "brand_id": 1,
            "country_id": 1,
            "gender": "Женские",
            "image_url": "/uploads/sneakers/nike_air_max.png",
        },
        {
            "name": "Yellow",
            "description": "Стильные желтые кроссовки для повседневной носки",
            "price": 134.50,
            "brand_id": 1,
            "country_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_yellow.jpg",
        },
        {
            "name": "AL8",
            "description": "Инновационная модель с улучшенной амортизацией",
            "price": 489.99,
            "brand_id": 1,
            "country_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_al8.png",
        },
        {
            "name": "DH",
            "description": "Спортивные кроссовки для динамичных тренировок",
            "price": 310.75,
            "brand_id": 1,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_dh.jpeg",
        },
        {
            "name": "DN",
            "description": "Элегантные кроссовки для городского стиля",
            "price": 195.20,
            "brand_id": 1,
            "country_id": 2,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_dn.jpg",
        },
        {
            "name": "Jordan",
            "description": "Культовая баскетбольная модель премиум-класса",
            "price": 500.00,
            "brand_id": 1,
            "country_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_jordan.jpg",
        },
        {
            "name": "React",
            "description": "Технологичные кроссовки с реактивной амортизацией",
            "price": 245.30,
            "brand_id": 1,
            "country_id": 11,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_react.jpg",
        },
        {
            "name": "Intertop",
            "description": "Универсальные кроссовки для активного образа жизни",
            "price": 165.80,
            "brand_id": 1,
            "country_id": 10,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_intertop.jpg",
        },
        {
            "name": "Ferrari",
            "description": "Эксклюзивная коллаборация с легендарным автобрендом",
            "price": 425.99,
            "brand_id": 3,
            "country_id": 10,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_ferrari.jpg",
        },
        {
            "name": "Palermo",
            "description": "Классические кроссовки в стиле ретро",
            "price": 180.75,
            "brand_id": 3,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_palermo.png",
        },
        {
            "name": "Park",
            "description": "Удобные кроссовки для прогулок по городу",
            "price": 305.40,
            "brand_id": 3,
            "country_id": 3,
            "gender": "женские",
            "image_url": "/uploads/sneakers/puma_Park.png",
        },
        {
            "name": "Roma",
            "description": "Стильные повседневные кроссовки с итальянским дизайном",
            "price": 125.99,
            "brand_id": 3,
            "country_id": 9,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_Roma.jpg",
        },
        {
            "name": "RS-X",
            "description": "Футуристичные кроссовки с геометрическим дизайном",
            "price": 410.50,
            "brand_id": 3,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_rs-x.png",
        },
        {
            "name": "SL",
            "description": "Легкие и компактные кроссовки для путешествий",
            "price": 350.25,
            "brand_id": 3,
            "country_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/puma_sl.png",
        },
        {
            "name": "Suede",
            "description": "Классические замшевые кроссовки для уличного стиля",
            "price": 270.80,
            "brand_id": 3,
            "country_id": 8,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_suede.jpg",
        },
        {
            "name": "Trinity",
            "description": "Технологичные кроссовки с тройной системой амортизации",
            "price": 199.99,
            "brand_id": 3,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_trinity.jpg",
        },
        {
            "name": "Authetic",
            "description": "Классические скейтерские кроссовки прямого покроя",
            "price": 490.50,
            "brand_id": 4,
            "country_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_authetic.png",
        },
        {
            "name": "Hevy",
            "description": "Прочные кроссовки для экстремальных видов спорта",
            "price": 130.99,
            "brand_id": 4,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_hevy.png",
        },
        {
            "name": "Old",
            "description": "Винтажные кроссовки в ретро-стиле",
            "price": 345.75,
            "brand_id": 4,
            "country_id": 8,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_old.jpg",
        },
        {
            "name": "Old Scholl",
            "description": "Традиционные скейтерские кроссовки с улучшенным комфортом",
            "price": 280.20,
            "brand_id": 4,
            "country_id": 4,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_old_scholl.png",
        },
        {
            "name": "Primary",
            "description": "Базовые кроссовки с минималистичным дизайном",
            "price": 220.65,
            "brand_id": 4,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_Primary.png",
        },
        {
            "name": "Ssk8",
            "description": "Профессиональные кроссовки для скейтбординга",
            "price": 495.99,
            "brand_id": 4,
            "country_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_Sk8.png",
        },
        {
            "name": "Skooll",
            "description": "Культовая модель для уличной моды",
            "price": 190.89,
            "brand_id": 4,
            "country_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_skool.png",
        },
        {
            "name": "Slip",
            "description": "Удобные кроссовки-слипоны для повседневной носки",
            "price": 310.50,
            "brand_id": 4,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_slip.jpg",
        },
        {
            "name": "Centennial",
            "description": "Юбилейная ограниченная серия премиум-класса",
            "price": 315.99,
            "brand_id": 2,
            "country_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_centennial.jpg",
        },
        {
            "name": "Byuty",
            "description": "Элегантные кроссовки для современного городского стиля",
            "price": 150.50,
            "brand_id": 2,
            "country_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_daroga.jpg",
        },
        {
            "name": "Eclyptix",
            "description": "Футуристичные кроссовки с уникальным дизайном",
            "price": 475.80,
            "brand_id": 2,
            "country_id": 4,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_eclyptix.png",
        },
        {
            "name": "Fenesi",
            "description": "Спортивные кроссовки для бега и тренировок",
            "price": 220.40,
            "brand_id": 2,
            "country_id": 5,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_fenesi.jpg",
        },
        {
            "name": "Ozweego",
            "description": "Стильные кроссовки с технологичной амортизацией",
            "price": 405.99,
            "brand_id": 2,
            "country_id": 5,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_ozweego.png",
        },
        {
            "name": "Runfalcon",
            "description": "Легкие беговые кроссовки для ежедневных тренировок",
            "price": 185.75,
            "brand_id": 2,
            "country_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_runfalcon.jpg",
        },
        {
            "name": "Temper",
            "description": "Универсальные кроссовки для активного отдыха",
            "price": 345.99,
            "brand_id": 2,
            "country_id": 6,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_runfalcon.png",
        },
        {
            "name": "Daffy",
            "description": "Комфортные кроссовки для длительных прогулок",
            "price": 260.30,
            "brand_id": 2,
            "country_id": 7,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_temper.jpg",
        },
    ]

    stmt = insert(Sneaker).values(sneakers)
    await session.execute(stmt)
    await session.commit()
