"""Indexes on Foreign keys have been added

Revision ID: 1a86c455d5c7
Revises: 689153d118fb
Create Date: 2025-12-20 05:21:46.971364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a86c455d5c7"
down_revision: Union[str, None] = "689153d118fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_blacklists_refresh_token_id"),
        "blacklists",
        ["refresh_token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_account_user_id"),
        "oauth_account",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"),
        "refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permission_associations_permission_id"),
        "role_permission_associations",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permission_associations_role_id"),
        "role_permission_associations",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_role_associations_role_id"),
        "user_role_associations",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_role_associations_user_id"),
        "user_role_associations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_role_associations_user_id"),
        table_name="user_role_associations",
    )
    op.drop_index(
        op.f("ix_user_role_associations_role_id"),
        table_name="user_role_associations",
    )
    op.drop_index(
        op.f("ix_role_permission_associations_role_id"),
        table_name="role_permission_associations",
    )
    op.drop_index(
        op.f("ix_role_permission_associations_permission_id"),
        table_name="role_permission_associations",
    )
    op.drop_index(
        op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens"
    )
    op.drop_index(op.f("ix_oauth_account_user_id"), table_name="oauth_account")
    op.drop_index(
        op.f("ix_blacklists_refresh_token_id"), table_name="blacklists"
    )
    # ### end Alembic commands ###
