"""Added cascading deletion and restrict

Revision ID: 689153d118fb
Revises: 41adb231713a
Create Date: 2025-12-17 22:29:15.347778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "689153d118fb"
down_revision: Union[str, None] = "41adb231713a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_blacklists_refresh_token_id_refresh_tokens"),
        "blacklists",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_blacklists_refresh_token_id_refresh_tokens"),
        "blacklists",
        "refresh_tokens",
        ["refresh_token_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_refresh_tokens_user_id_users"),
        "refresh_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refresh_tokens_user_id_users"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_role_permission_associations_permission_id_permissions"),
        "role_permission_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_role_permission_associations_role_id_roles"),
        "role_permission_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_role_permission_associations_role_id_roles"),
        "role_permission_associations",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_role_permission_associations_permission_id_permissions"),
        "role_permission_associations",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_user_role_associations_user_id_users"),
        "user_role_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_role_associations_role_id_roles"),
        "user_role_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_role_associations_user_id_users"),
        "user_role_associations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_role_associations_role_id_roles"),
        "user_role_associations",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_role_associations_role_id_roles"),
        "user_role_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_role_associations_user_id_users"),
        "user_role_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_role_associations_role_id_roles"),
        "user_role_associations",
        "roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_role_associations_user_id_users"),
        "user_role_associations",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_role_permission_associations_permission_id_permissions"),
        "role_permission_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_role_permission_associations_role_id_roles"),
        "role_permission_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_role_permission_associations_role_id_roles"),
        "role_permission_associations",
        "roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_role_permission_associations_permission_id_permissions"),
        "role_permission_associations",
        "permissions",
        ["permission_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_refresh_tokens_user_id_users"),
        "refresh_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refresh_tokens_user_id_users"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_blacklists_refresh_token_id_refresh_tokens"),
        "blacklists",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_blacklists_refresh_token_id_refresh_tokens"),
        "blacklists",
        "refresh_tokens",
        ["refresh_token_id"],
        ["id"],
    )
    # ### end Alembic commands ###
