from fastapi import APIRouter
from sneaker_views_history_service.user_history.routers.get_history_recent import router as recent_history_sneakers_views_router
from sneaker_views_history_service.user_history.routers.get_history import router as history_sneakers_views_router

router = APIRouter()

router.include_router(recent_history_sneakers_views_router)
router.include_router(history_sneakers_views_router)
