"""Indexes on Foreign keys have been added

Revision ID: 83863189e332
Revises: a734bb19bbb4
Create Date: 2025-12-20 05:24:33.962082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83863189e332"
down_revision: Union[str, None] = "a734bb19bbb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_favorite_sneaker_associations_favorite_id"),
        "favorite_sneaker_associations",
        ["favorite_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_sneaker_associations_size_id"),
        "favorite_sneaker_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_sneaker_associations_sneaker_id"),
        "favorite_sneaker_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_sneaker_id"),
        table_name="favorite_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_size_id"),
        table_name="favorite_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_favorite_id"),
        table_name="favorite_sneaker_associations",
    )
    # ### end Alembic commands ###
