"""Refinement of table field properties

Revision ID: 6939d8d498dd
Revises: 83863189e332
Create Date: 2025-12-27 07:41:33.577311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6939d8d498dd"
down_revision: Union[str, None] = "83863189e332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.create_unique_constraint(
        op.f("uq_brands_image_url"), "brands", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_brands_name"), "brands", ["name"])
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_favorite_id"),
        table_name="favorite_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_size_id"),
        table_name="favorite_sneaker_associations",
    )
    op.drop_index(
        op.f("ix_favorite_sneaker_associations_sneaker_id"),
        table_name="favorite_sneaker_associations",
    )
    op.create_unique_constraint(
        "uq_favorite_sneaker_size",
        "favorite_sneaker_associations",
        ["favorite_id", "sneaker_id", "size_id"],
    )
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.create_unique_constraint(
        op.f("uq_favorites_user_id"), "favorites", ["user_id"]
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(op.f("ix_sneakers_name"), table_name="sneakers")
    op.create_unique_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_sneakers_name"), "sneakers", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sneakers_name"), "sneakers", type_="unique")
    op.drop_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", type_="unique"
    )
    op.create_index(
        op.f("ix_sneakers_name"), "sneakers", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("uq_favorites_user_id"), "favorites", type_="unique"
    )
    op.create_index(
        op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=True
    )
    op.drop_constraint(
        "uq_favorite_sneaker_size",
        "favorite_sneaker_associations",
        type_="unique",
    )
    op.create_index(
        op.f("ix_favorite_sneaker_associations_sneaker_id"),
        "favorite_sneaker_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_sneaker_associations_size_id"),
        "favorite_sneaker_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_sneaker_associations_favorite_id"),
        "favorite_sneaker_associations",
        ["favorite_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_brands_name"), "brands", type_="unique")
    op.drop_constraint(op.f("uq_brands_image_url"), "brands", type_="unique")
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    # ### end Alembic commands ###
