"""Added cascading deletion and restrict

Revision ID: a734bb19bbb4
Revises: 62b82ba88faf
Create Date: 2025-12-17 20:27:44.500734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a734bb19bbb4"
down_revision: Union[str, None] = "62b82ba88faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_favorite_id_favorites"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_sneaker_id_sneakers"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_favorite_id_favorites"),
        "favorite_sneaker_associations",
        "favorites",
        ["favorite_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_sneaker_id_sneakers"),
        "favorite_sneaker_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_sneaker_id_sneakers"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_favorite_id_favorites"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_size_id_sizes"),
        "favorite_sneaker_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_sneaker_id_sneakers"),
        "favorite_sneaker_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_favorite_sneaker_associations_favorite_id_favorites"),
        "favorite_sneaker_associations",
        "favorites",
        ["favorite_id"],
        ["id"],
    )
    # ### end Alembic commands ###
