"""Create Brand, Size, Sneaker, SneakerSizeAssociation tables

Revision ID: c55ee888dbcc
Revises: f241b4ea9505
Create Date: 2025-05-08 01:29:02.383230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c55ee888dbcc"
down_revision: Union[str, None] = "f241b4ea9505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("image_url", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    op.create_table(
        "sizes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eu_size", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.CheckConstraint(
            "eu_size BETWEEN 15 AND 50",
            name=op.f("ck_sizes_check_eu_size_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sizes")),
        sa.UniqueConstraint("eu_size", name=op.f("uq_sizes_eu_size")),
    )
    op.create_table(
        "sneakers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "price > 0", name=op.f("ck_sneakers_check_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_sneakers_brand_id_brands"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sneakers")),
    )
    op.create_index(
        op.f("ix_sneakers_brand_id"), "sneakers", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_sneakers_name"), "sneakers", ["name"], unique=False
    )
    op.create_table(
        "sneaker_size_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("size_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["size_id"],
            ["sizes.id"],
            name=op.f("fk_sneaker_size_associations_size_id_sizes"),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_sneaker_size_associations")
        ),
        sa.UniqueConstraint("sneaker_id", "size_id", name="uq_sneaker_size"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sneaker_size_associations")
    op.drop_index(op.f("ix_sneakers_name"), table_name="sneakers")
    op.drop_index(op.f("ix_sneakers_brand_id"), table_name="sneakers")
    op.drop_table("sneakers")
    op.drop_table("sizes")
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
