"""Added cascading deletion and restrict

Revision ID: fde5eeacd1de
Revises: f02aa464cdf9
Create Date: 2025-12-17 21:14:06.674551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fde5eeacd1de"
down_revision: Union[str, None] = "f02aa464cdf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    # ### end Alembic commands ###
