from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from catalog_service.catalog.models import Sneaker


async def seed_sneakers(session: AsyncSession):
    sneakers = [
        {
            "name": "Air Max",
            "price": 215.90,
            "brand_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_air_max.png",
        },
        {
            "name": "Yellow",
            "price": 134.50,
            "brand_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_yellow.jpg",
        },
        {
            "name": "AL8",
            "price": 489.99,
            "brand_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_al8.png",
        },
        {
            "name": "DH",
            "price": 310.75,
            "brand_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_dh.jpeg",
        },
        {
            "name": "DN",
            "price": 195.20,
            "brand_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_dn.jpg",
        },
        {
            "name": "Jordan",
            "price": 500.00,
            "brand_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_jordan.jpg",
        },
        {
            "name": "React",
            "price": 245.30,
            "brand_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_react.jpg",
        },
        {
            "name": "Intertop",
            "price": 165.80,
            "brand_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_intertop.jpg",
        },
        {
            "name": "Ferrari",
            "price": 425.99,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_ferrari.jpg",
        },
        {
            "name": "Palermo",
            "price": 180.75,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_palermo.png",
        },
        {
            "name": "Park",
            "price": 305.40,
            "brand_id": 3,
            "gender": "женские",
            "image_url": "/uploads/sneakers/puma_Park.png",
        },
        {
            "name": "Roma",
            "price": 125.99,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_Roma.jpg",
        },
        {
            "name": "RS-X",
            "price": 410.50,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_rs-x.png",
        },
        {
            "name": "SL",
            "price": 350.25,
            "brand_id": 3,
            "gender": "женские",
            "image_url": "/uploads/sneakers/puma_sl.png",
        },
        {
            "name": "Suede",
            "price": 270.80,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_suede.jpg",
        },
        {
            "name": "Trinity",
            "price": 199.99,
            "brand_id": 3,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/puma_trinity.jpg",
        },
        {
            "name": "Authetic",
            "price": 490.50,
            "brand_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_authetic.png",
        },
        {
            "name": "Hevy",
            "price": 130.99,
            "brand_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_hevy.png",
        },
        {
            "name": "Old",
            "price": 345.75,
            "brand_id": 4,
            "image_url": "/uploads/sneakers/vans_old.jpg",
        },
        {
            "name": "Old Scholl",
            "price": 280.00,
            "brand_id": 4,
            "image_url": "/uploads/sneakers/vans_old_scholl.png",
        },
        {
            "name": "Primary",
            "price": 220.65,
            "brand_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_Primary.png",
        },
        {
            "name": "Ssk8",
            "price": 495.99,
            "brand_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_Sk8.png",
        },
        {
            "name": "Skooll",
            "price": 190.89,
            "brand_id": 4,
            "image_url": "/uploads/sneakers/vans_skool.png",
        },
        {
            "name": "Slip",
            "price": 310.50,
            "brand_id": 4,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/vans_slip.jpg",
        },
        {
            "name": "Centennial",
            "price": 315.99,
            "brand_id": 2,
            "image_url": "/uploads/sneakers/adidas_centennial.jpg",
        },
        {
            "name": "Byuty",
            "price": 150.50,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_daroga.jpg",
        },
        {
            "name": "Eclyptix",
            "price": 475.80,
            "brand_id": 2,
            "image_url": "/uploads/sneakers/adidas_eclyptix.png",
        },
        {
            "name": "Fenesi",
            "price": 220.40,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_fenesi.jpg",
        },
        {
            "name": "Ozweego",
            "price": 405.99,
            "brand_id": 2,
            "image_url": "/uploads/sneakers/adidas_ozweego.png",
        },
        {
            "name": "Runfalcon",
            "price": 185.75,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_runfalcon.jpg",
        },
        {
            "name": "Temper",
            "price": 345.99,
            "brand_id": 2,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_runfalcon.png",
        },
        {
            "name": "Daffy",
            "price": 260.30,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_temper.jpg",
        },
    ]

    stmt = insert(Sneaker).values(sneakers)
    await session.execute(stmt)
    await session.commit()
