"""Drop gender in table sneakers

Revision ID: 52f94c9bf2ac
Revises: 88382d7672ab
Create Date: 2025-05-08 22:09:12.915945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52f94c9bf2ac"
down_revision: Union[str, None] = "88382d7672ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneakers", "gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneakers",
        sa.Column(
            "gender",
            postgresql.ENUM("male", "female", "unisex", name="genderenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
