"""Update table sneakers

Revision ID: 88382d7672ab
Revises: c55ee888dbcc
Create Date: 2025-05-08 21:27:28.355829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88382d7672ab"
down_revision: Union[str, None] = "c55ee888dbcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


gender_enum = sa.Enum("male", "female", "unisex", name="genderenum")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum.create(op.get_bind())

    op.add_column(
        "sneakers",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "sneakers",
        sa.Column(
            "gender",
            gender_enum,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneakers", "gender")
    op.drop_column("sneakers", "created_at")

    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
