"""Add gender in table sneakers

Revision ID: 4ecf9d6ff384
Revises: 52f94c9bf2ac
Create Date: 2025-05-09 00:40:27.081421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ecf9d6ff384"
down_revision: Union[str, None] = "52f94c9bf2ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneakers", sa.Column("gender", sa.String(length=10), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneakers", "gender")
    # ### end Alembic commands ###
