"""Refinement of table field properties

Revision ID: 7d85238c2dbc
Revises: aface7f26fe4
Create Date: 2025-12-27 07:42:52.767684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d85238c2dbc"
down_revision: Union[str, None] = "aface7f26fe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.create_unique_constraint(
        op.f("uq_brands_image_url"), "brands", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_brands_name"), "brands", ["name"])
    op.drop_index(op.f("ix_colors_name"), table_name="colors")
    op.create_unique_constraint(op.f("uq_colors_name"), "colors", ["name"])
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.create_unique_constraint(
        op.f("uq_countries_name"), "countries", ["name"]
    )
    op.drop_index(op.f("ix_materials_name"), table_name="materials")
    op.create_unique_constraint(
        op.f("uq_materials_name"), "materials", ["name"]
    )
    op.drop_index(
        op.f("ix_sneaker_color_associations_color_id"),
        table_name="sneaker_color_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_color_associations_sneaker_id"),
        table_name="sneaker_color_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_material_associations_material_id"),
        table_name="sneaker_material_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_material_associations_sneaker_id"),
        table_name="sneaker_material_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(op.f("ix_sneakers_name"), table_name="sneakers")
    op.create_unique_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", ["image_url"]
    )
    op.create_unique_constraint(op.f("uq_sneakers_name"), "sneakers", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sneakers_name"), "sneakers", type_="unique")
    op.drop_constraint(
        op.f("uq_sneakers_image_url"), "sneakers", type_="unique"
    )
    op.create_index(
        op.f("ix_sneakers_name"), "sneakers", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_material_associations_sneaker_id"),
        "sneaker_material_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_material_associations_material_id"),
        "sneaker_material_associations",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_color_associations_sneaker_id"),
        "sneaker_color_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_color_associations_color_id"),
        "sneaker_color_associations",
        ["color_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_materials_name"), "materials", type_="unique")
    op.create_index(
        op.f("ix_materials_name"), "materials", ["name"], unique=True
    )
    op.drop_constraint(op.f("uq_countries_name"), "countries", type_="unique")
    op.create_index(
        op.f("ix_countries_name"), "countries", ["name"], unique=True
    )
    op.drop_constraint(op.f("uq_colors_name"), "colors", type_="unique")
    op.create_index(op.f("ix_colors_name"), "colors", ["name"], unique=True)
    op.drop_constraint(op.f("uq_brands_name"), "brands", type_="unique")
    op.drop_constraint(op.f("uq_brands_image_url"), "brands", type_="unique")
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    # ### end Alembic commands ###
