"""Adding the is_active field to the table sneaker_size_associations

Revision ID: cbc4b729a2ec
Revises: 7d85238c2dbc
Create Date: 2025-12-27 07:54:09.490396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbc4b729a2ec"
down_revision: Union[str, None] = "7d85238c2dbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sneaker_size_associations",
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sneaker_size_associations", "is_active")
    # ### end Alembic commands ###
