from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from microservices.cart_service.cart_service.cart.models import Sneaker


async def seed_sneakers(session: AsyncSession):
    sneakers = [
        {
            "name": "Air Zoom Pegasus",
            "price": 399.99,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_pegasus.png",
        },
        {
            "name": "Ultraboost Classic",
            "price": 429.50,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_ultraboost.png",
        },
        {
            "name": "RS-X Bold",
            "price": 349.00,
            "brand_id": 3,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/puma_rsx.png",
        },
        {
            "name": "Old Skool Canvas",
            "price": 270.00,
            "brand_id": 4,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_oldskool.png",
        },
        {
            "name": "XT-6 Trail",
            "price": 460.00,
            "brand_id": 5,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_xt6.png",
        },
        {
            "name": "Gel-Kayano 28",
            "price": 420.50,
            "brand_id": 6,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/asics_kayano.png",
        },
        {
            "name": "Fresh Foam X",
            "price": 389.00,
            "brand_id": 7,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/newbalance_freshfoam.png",
        },
        {
            "name": "Classic Leather",
            "price": 310.00,
            "brand_id": 8,
            "gender": "женские",
            "image_url": "/uploads/sneakers/reebok_classic.png",
        },
        {
            "name": "Chuck Taylor All Star",
            "price": 280.00,
            "brand_id": 9,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/converse_chuck.png",
        },
        {
            "name": "Air Jordan 1",
            "price": 520.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_1.png",
        },
        {
            "name": "HOVR Phantom",
            "price": 375.00,
            "brand_id": 11,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/underarmour_hovr.png",
        },
        {
            "name": "Kinvara Lite",
            "price": 299.99,
            "brand_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/saucony_kinvara.png",
        },
        {
            "name": "Disruptor II",
            "price": 299.99,
            "brand_id": 13,
            "gender": "женские",
            "image_url": "/uploads/sneakers/fila_disruptor.png",
        },
        {
            "name": "Clifton",
            "price": 410.00,
            "brand_id": 14,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/hoka_clifton.png",
        },
        {
            "name": "Wave Rider",
            "price": 365.00,
            "brand_id": 15,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/mizuno_waverider.png",
        },
        {
            "name": "N9000",
            "price": 330.00,
            "brand_id": 16,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/diadora_n9000.png",
        },
        {
            "name": "Ghost",
            "price": 359.00,
            "brand_id": 17,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/brooks_ghost.png",
        },
        {
            "name": "Retro",
            "price": 245.00,
            "brand_id": 18,
            "gender": "женские",
            "image_url": "/uploads/sneakers/kappa_retro.png",
        },
        {
            "name": "Trail Runner Pro",
            "price": 439.00,
            "brand_id": 5,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_trail.png",
        },
        {
            "name": "City Walker",
            "price": 219.99,
            "brand_id": 8,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/reebok_citywalker.png",
        },
        {
            "name": "Skate Pro",
            "price": 289.00,
            "brand_id": 4,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/vans_skatepro.png",
        },
        {
            "name": "Court Classic",
            "price": 255.00,
            "brand_id": 9,
            "gender": "женские",
            "image_url": "/uploads/sneakers/converse_court.png",
        },
        {
            "name": "Speedster",
            "price": 499.00,
            "brand_id": 1,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/nike_speedster.png",
        },
        {
            "name": "Everyday Comfort",
            "price": 199.99,
            "brand_id": 7,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/newbalance_everyday.png",
        },
        {
            "name": "Court Ace",
            "price": 279.50,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_courtace.png",
        },
        {
            "name": "Urban Runner",
            "price": 325.00,
            "brand_id": 3,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/puma_urbanrunner.png",
        },
        {
            "name": "Retro Runner",
            "price": 289.99,
            "brand_id": 13,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/fila_retrorunner.png",
        },
        {
            "name": "All Terrain GTX",
            "price": 499.99,
            "brand_id": 5,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/salomon_gtx.png",
        },
        {
            "name": "Minimal Trainer",
            "price": 219.00,
            "brand_id": 12,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/saucony_minimal.png",
        },
        {
            "name": "Heritage Classic",
            "price": 349.00,
            "brand_id": 8,
            "gender": "женские",
            "image_url": "/uploads/sneakers/reebok_heritage.png",
        },
        {
            "name": "Air Force 1 Low",
            "price": 329.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_low.png",
        },
        {
            "name": "Dunk Low Retro",
            "price": 349.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_low.png",
        },
        {
            "name": "Jordan 4 Retro",
            "price": 599.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4.png",
        },
        {
            "name": "Jordan 11 Concord",
            "price": 749.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_concord.png",
        },
        {
            "name": "Jordan 5 Retro",
            "price": 529.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5.png",
        },
        {
            "name": "Jordan 6 Retro",
            "price": 549.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_6.png",
        },
        {
            "name": "Jordan 7 Retro",
            "price": 499.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_7.png",
        },
        {
            "name": "Air Force 1 High",
            "price": 349.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_high.png",
        },
        {
            "name": "Dunk High Premium",
            "price": 369.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_high.png",
        },
        {
            "name": "Air Force 1 Shadow",
            "price": 339.00,
            "brand_id": 1,
            "gender": "женские",
            "image_url": "/uploads/sneakers/nike_af1_shadow.png",
        },
        {
            "name": "Superstar Classic",
            "price": 299.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar.png",
        },
        {
            "name": "Spezial OG",
            "price": 319.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial.png",
        },
        {
            "name": "Forum Low",
            "price": 289.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_forum.png",
        },
        {
            "name": "Yeezy Runner (inspired)",
            "price": 429.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_yeezy_like.png",
        },
        {
            "name": "Campus 80s",
            "price": 279.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_campus.png",
        },
        {
            "name": "Gazelle Vintage",
            "price": 259.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_gazelle.png",
        },
        {
            "name": "Stan Smith Premium",
            "price": 299.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_stansmith.png",
        },
        {
            "name": "Superstar Bold",
            "price": 329.00,
            "brand_id": 2,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_superstar_bold.png",
        },
        {
            "name": "Dame Retro (inspired)",
            "price": 279.00,
            "brand_id": 2,
            "gender": "мужские",
            "image_url": "/uploads/sneakers/adidas_dame_like.png",
        },
        {
            "name": "Spezial Low",
            "price": 309.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial_low.png",
        },
        {
            "name": "Air Force 1 Utility",
            "price": 359.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_utility.png",
        },
        {
            "name": "Dunk SB Pro",
            "price": 379.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_sb.png",
        },
        {
            "name": "Jordan 4 Retro SE",
            "price": 629.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4_se.png",
        },
        {
            "name": "Jordan 5 Off-White (inspired)",
            "price": 699.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5_collab.png",
        },
        {
            "name": "Superstar Platform",
            "price": 339.00,
            "brand_id": 2,
            "gender": "женские",
            "image_url": "/uploads/sneakers/adidas_superstar_platform.png",
        },
        {
            "name": "Dunk Low Premium Pack",
            "price": 389.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_premium.png",
        },
        {
            "name": "Jordan 11 Retro Low",
            "price": 699.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_low.png",
        },
        {
            "name": "Air Force 1 Pixel",
            "price": 349.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_pixel.png",
        },
        {
            "name": "Superstar Vintage",
            "price": 309.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar_vintage.png",
        },
        {
            "name": "Dunk Low City Pack",
            "price": 369.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_citypack.png",
        },
        {
            "name": "Air Force 1 Low Premium",
            "price": 359.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_premium.png",
        },
        {
            "name": "Dunk Low Retro OG",
            "price": 379.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_dunk_low_og.png",
        },
        {
            "name": "Jordan 4 Retro OG",
            "price": 619.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_4_og.png",
        },
        {
            "name": "Jordan 11 Retro IE",
            "price": 699.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_11_ie.png",
        },
        {
            "name": "Jordan 5 Retro Low",
            "price": 529.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_5_low.png",
        },
        {
            "name": "Superstar Core",
            "price": 289.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_superstar_core.png",
        },
        {
            "name": "Spezial Reissue",
            "price": 329.00,
            "brand_id": 2,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/adidas_spezial_reissue.png",
        },
        {
            "name": "Air Jordan 6 Retro",
            "price": 549.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_6_retro.png",
        },
        {
            "name": "Air Jordan 7 Retro Low",
            "price": 499.00,
            "brand_id": 10,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/jordan_7_low.png",
        },
        {
            "name": "Air Force 1 Utility Mid",
            "price": 369.00,
            "brand_id": 1,
            "gender": "унисекс",
            "image_url": "/uploads/sneakers/nike_af1_utility_mid.png",
        },
    ]

    stmt = insert(Sneaker).values(sneakers)
    await session.execute(stmt)
    await session.commit()
