"""Creating the following tables: Sneakers, Brands, Users, UserSneakerSubscription

Revision ID: 868aef7762e6
Revises: 
Create Date: 2025-11-28 09:59:32.875987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868aef7762e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_sneakers_brand_id_brands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sneakers'))
    )
    op.create_index(op.f('ix_sneakers_brand_id'), 'sneakers', ['brand_id'], unique=False)
    op.create_index(op.f('ix_sneakers_name'), 'sneakers', ['name'], unique=False)
    op.create_table('user_sneaker_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sneaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], name=op.f('fk_user_sneaker_subscriptions_sneaker_id_sneakers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sneaker_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sneaker_subscriptions')),
    sa.UniqueConstraint('sneaker_id', 'user_id', name='uq_user_sneaker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sneaker_subscriptions')
    op.drop_index(op.f('ix_sneakers_name'), table_name='sneakers')
    op.drop_index(op.f('ix_sneakers_brand_id'), table_name='sneakers')
    op.drop_table('sneakers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
