"""Added cascading deletion and restrict

Revision ID: df68096dc49f
Revises: cb8c6f918d25
Create Date: 2025-12-17 21:30:29.672734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df68096dc49f"
down_revision: Union[str, None] = "cb8c6f918d25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_user_id_users"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_sneaker_id_sneakers"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_user_id_users"),
        "user_sneaker_subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        "sizes",
        ["size_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_sneaker_id_sneakers"),
        "user_sneaker_subscriptions",
        "sneakers",
        ["sneaker_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_sneaker_id_sneakers"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_sneaker_subscriptions_user_id_users"),
        "user_sneaker_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_size_id_sizes"),
        "user_sneaker_subscriptions",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_sneaker_id_sneakers"),
        "user_sneaker_subscriptions",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_sneaker_subscriptions_user_id_users"),
        "user_sneaker_subscriptions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneakers_brand_id_brands"), "sneakers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_sneakers_brand_id_brands"),
        "sneakers",
        "brands",
        ["brand_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_size_id_sizes"),
        "sneaker_size_associations",
        "sizes",
        ["size_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        "sneaker_size_associations",
        "sneakers",
        ["sneaker_id"],
        ["id"],
    )
    # ### end Alembic commands ###
