"""Indexes on Foreign keys have been added

Revision ID: 40b7b645a180
Revises: df68096dc49f
Create Date: 2025-12-20 05:27:04.547567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40b7b645a180"
down_revision: Union[str, None] = "df68096dc49f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sneaker_size_associations_size_id"),
        "sneaker_size_associations",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        "sneaker_size_associations",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sneaker_subscriptions_size_id"),
        "user_sneaker_subscriptions",
        ["size_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sneaker_subscriptions_sneaker_id"),
        "user_sneaker_subscriptions",
        ["sneaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sneaker_subscriptions_user_id"),
        "user_sneaker_subscriptions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_sneaker_subscriptions_user_id"),
        table_name="user_sneaker_subscriptions",
    )
    op.drop_index(
        op.f("ix_user_sneaker_subscriptions_sneaker_id"),
        table_name="user_sneaker_subscriptions",
    )
    op.drop_index(
        op.f("ix_user_sneaker_subscriptions_size_id"),
        table_name="user_sneaker_subscriptions",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_sneaker_id"),
        table_name="sneaker_size_associations",
    )
    op.drop_index(
        op.f("ix_sneaker_size_associations_size_id"),
        table_name="sneaker_size_associations",
    )
    # ### end Alembic commands ###
