"""Add tables sizes, sneaker_size_associations

Revision ID: 0d0fef4039fc
Revises: 868aef7762e6
Create Date: 2025-12-02 09:49:36.643711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d0fef4039fc"
down_revision: Union[str, None] = "868aef7762e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sizes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eu_size", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.CheckConstraint(
            "eu_size BETWEEN 15 AND 50",
            name=op.f("ck_sizes_check_eu_size_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sizes")),
        sa.UniqueConstraint("eu_size", name=op.f("uq_sizes_eu_size")),
    )
    op.create_table(
        "sneaker_size_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sneaker_id", sa.Integer(), nullable=False),
        sa.Column("size_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["size_id"],
            ["sizes.id"],
            name=op.f("fk_sneaker_size_associations_size_id_sizes"),
        ),
        sa.ForeignKeyConstraint(
            ["sneaker_id"],
            ["sneakers.id"],
            name=op.f("fk_sneaker_size_associations_sneaker_id_sneakers"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_sneaker_size_associations")
        ),
        sa.UniqueConstraint("sneaker_id", "size_id", name="uq_sneaker_size"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sneaker_size_associations")
    op.drop_table("sizes")
    # ### end Alembic commands ###
